"""new fields in user model

Revision ID: 16159df815c1
Revises: 294be7066a7a
Create Date: 2020-02-11 09:38:05.759972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16159df815c1'
down_revision = '294be7066a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
